version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: CanzShopDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8888:8080
    depends_on:
      - postgres
  web: 
    restart: always
    container_name: web-app
    build: ./web
    ports:
      - 9090:9090
    depends_on:
      - postgres

volumes:
  postgres_data: